# Data Cleaing

In [12]:
import pandas as pd
import numpy as np

# Load your CSV file into a pandas DataFrame
df = pd.read_csv('Final-censusdataset-India.csv')
print(df.head())

   sr    state                                           District   person  \
0   1  ANdaman  District Nicobars (01), Andaman & Nicobar Isla...   314084
1   2  ANdaman  District Nicobars (02), Andaman & Nicobar Isla...    42068
2   3   Andhra        District Adilabad (01), Andhra Pradesh (28)  2488003
3   4   Andhra       District Nizamabad (02), Andhra Pradesh (28)  2345685
4   5   Andhra      District Karimnagar (03), Andhra Pradesh (28)  3491822

      Male   Female  growthinpopulation    rural   urban  urban.1  ...  \
0   170319   143765               30.14   197886  116198    844.0  ...
1    22653    19415                7.19    42068       -    857.0  ...
2  1250958  1237045               19.06  1827986     NaN    989.0  ...
3  1162905  1182780               14.98  1920947     NaN   1017.0  ...
4  1747968  1743854               14.47  2813010     NaN    998.0  ...

  religion1 population     Religion2  Religion2 Population  religion3name  \
0               235862  2.Christians                 49033      3.Muslims
1                28145      2.Hindus                 10727      3.Muslims
2              2207843           NaN                236844            NaN
3              1983275     2.Muslims                338824   3.Christians
4              3251834     2.Muslims                213811   3.Christians

   religion3poulation  inhabitadevillages  drinkingwater  electricity  \
0               27134               331.0          331.0        233.0
1                2131               170.0          169.0         96.0
2               24392              1586.0         1585.0       1585.0
3               16204               854.0          854.0        854.0
4               20576              1047.0         1047.0       1047.0

  primary school  Medical facility
0          185.0               102
1           53.0                38
2         1521.0               976
3          839.0               614
4         1039.0               863

[5 rows x 29 columns]

In [3]:
# df is our DataFrame and 'urban' is the column we want to drop
df = df.drop('urban', axis=1)
df.head(3)

,sr,state,District,person,Male,Female,growthinpopulation,rural,urban.1,STPop,...,religion1 population,Religion2,Religion2 Population,religion3name,religion3poulation,inhabitadevillages,drinkingwater,electricity,primary school,Medical facility
0,1,ANdaman,"District Nicobars (01), Andaman & Nicobar Isla...",314084,170319,143765,30.14,197886,844.0,2904,...,235862,2.Christians,49033,3.Muslims,27134,331.0,331.0,233.0,185.0,102
1,2,ANdaman,"District Nicobars (02), Andaman & Nicobar Isla...",42068,22653,19415,7.19,42068,857.0,26565,...,28145,2.Hindus,10727,3.Muslims,2131,170.0,169.0,96.0,53.0,38
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986,989.0,416511,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976

In [4]:
import pandas as pd

# df is our DataFrame and 'urban.1' is the column we want to rename
df = df.rename(columns={'urban.1': 'urban'})
df.head(3)

,sr,state,District,person,Male,Female,growthinpopulation,rural,urban,STPop,...,religion1 population,Religion2,Religion2 Population,religion3name,religion3poulation,inhabitadevillages,drinkingwater,electricity,primary school,Medical facility
0,1,ANdaman,"District Nicobars (01), Andaman & Nicobar Isla...",314084,170319,143765,30.14,197886,844.0,2904,...,235862,2.Christians,49033,3.Muslims,27134,331.0,331.0,233.0,185.0,102
1,2,ANdaman,"District Nicobars (02), Andaman & Nicobar Isla...",42068,22653,19415,7.19,42068,857.0,26565,...,28145,2.Hindus,10727,3.Muslims,2131,170.0,169.0,96.0,53.0,38
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986,989.0,416511,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976

In [5]:
# Print the number of duplicates, if any
print("Number of duplicate rows: ", df.duplicated().sum())

# Drop the duplicates 
df = df.drop_duplicates()

# Print the number of duplicates again to confirm they've been dropped
print("Number of duplicate rows after dropping: ", df.duplicated().sum())

Number of duplicate rows:  0
Number of duplicate rows after dropping:  0

In [6]:
# Determine the number of missing values in each column
print("Number of missing values in each column:\n", df.isnull().sum())

Number of missing values in each column:
 sr                       0
state                    0
District                 0
person                   0
Male                     0
Female                   0
growthinpopulation       0
rural                    0
urban                    3
STPop                    3
Personlit_rate           0
Mlit_Rate                0
Flit_Rate                0
Totalworkers             0
Mainworkers              0
Marginal workers         0
Nonworkers               0
Religion1               53
religion1 population     0
Religion2               53
Religion2 Population     0
religion3name           53
religion3poulation       0
inhabitadevillages      12
drinkingwater           12
electricity             12
primary school          12
Medical facility        12
dtype: int64

In [7]:
# Fill missing numeric values with the mean
numeric_columns = df.select_dtypes(include=[np.number]).columns
df[numeric_columns] = df[numeric_columns].apply(lambda x: x.fillna(x.mean()))

# Fill missing non-numeric values
non_numeric_columns = df.select_dtypes(exclude=[np.number]).columns
df[non_numeric_columns] = df[non_numeric_columns].apply(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else ''))

df.to_csv('EDA1.csv', index=False)

In [8]:
print("Number of missing values in each column after filling:\n", df.isnull().sum())

Number of missing values in each column after filling:
 sr                      0
state                   0
District                0
person                  0
Male                    0
Female                  0
growthinpopulation      0
rural                   0
urban                   0
STPop                   0
Personlit_rate          0
Mlit_Rate               0
Flit_Rate               0
Totalworkers            0
Mainworkers             0
Marginal workers        0
Nonworkers              0
Religion1               0
religion1 population    0
Religion2               0
Religion2 Population    0
religion3name           0
religion3poulation      0
inhabitadevillages      0
drinkingwater           0
electricity             0
primary school          0
Medical facility        0
dtype: int64

In [9]:
df.head(3)

,sr,state,District,person,Male,Female,growthinpopulation,rural,urban,STPop,...,religion1 population,Religion2,Religion2 Population,religion3name,religion3poulation,inhabitadevillages,drinkingwater,electricity,primary school,Medical facility
0,1,ANdaman,"District Nicobars (01), Andaman & Nicobar Isla...",314084,170319,143765,30.14,197886,844.0,2904,...,235862,2.Christians,49033,3.Muslims,27134,331.0,331.0,233.0,185.0,102
1,2,ANdaman,"District Nicobars (02), Andaman & Nicobar Isla...",42068,22653,19415,7.19,42068,857.0,26565,...,28145,2.Hindus,10727,3.Muslims,2131,170.0,169.0,96.0,53.0,38
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986,989.0,416511,...,2207843,2.Muslims,236844,3.Christians,24392,1586.0,1585.0,1585.0,1521.0,976

### Fixing district names

In [13]:
import pandas as pd

# Read the CSV file as a data frame
df = pd.read_csv('EDA1.csv')

# Extract district names
df['District'] = df['District'].str.split('(').str[0].str.strip().str.split(' ').str[-1]
# Save the modified data frame to a CSV file
df.to_csv('EDA2(District_name).csv', index=False)

In [14]:
df.head(3)

,sr,state,District,person,Male,Female,growthinpopulation,rural,urban,STPop,...,religion1 population,Religion2,Religion2 Population,religion3name,religion3poulation,inhabitadevillages,drinkingwater,electricity,primary school,Medical facility
0,1,ANdaman,Nicobars,314084,170319,143765,30.14,197886,844.0,2904,...,235862,2.Christians,49033,3.Muslims,27134,331.0,331.0,233.0,185.0,102
1,2,ANdaman,Nicobars,42068,22653,19415,7.19,42068,857.0,26565,...,28145,2.Hindus,10727,3.Muslims,2131,170.0,169.0,96.0,53.0,38
2,3,Andhra,Adilabad,2488003,1250958,1237045,19.06,1827986,989.0,416511,...,2207843,2.Muslims,236844,3.Christians,24392,1586.0,1585.0,1585.0,1521.0,976

# Find outliers

In [15]:
from scipy import stats

# Calculate Z-scores
z_scores = stats.zscore(df.select_dtypes(include=['int', 'float']))

# Find outliers
outliers = df[(z_scores < -3) | (z_scores > 3)].any(axis=1)

# Print outliers
print("Outliers:",df[outliers])

Outliers:       sr             state       District   person     Male   Female  \
6      7            Andhra      Hyderabad  3829753  1981173  1848580
14    15            Andhra  Visakhapatnam  3832336  1930197  1902139
17    18            Andhra         Guntur  4465144  2250279  2214865
27    28  ArunachalPradesh              *   122003    64184    57819
112  113      Chhattisgarh     Dantewada*   719487   356928   362559
..   ...               ...            ...      ...      ...      ...
582  583        WestBengal       Parganas  8934286  4638756  4295530
584  585        WestBengal        Bankura  3192695  1636002  1556693
585  586        WestBengal       Puruliya  2536516  1298078  1238438
586  587        WestBengal      Medinipur  9610788  4916370  4694418
589  590        WestBengal       Parganas  6906689  3564993  3341696

     growthinpopulation    rural   urban   STPop  ...  religion1 population  \
6                 17.18        -   933.0   34560  ...               2121963
14                15.36  2301437   985.0  557572  ...               3688280
17                 7.27  3179384   984.0  208157  ...               3834204
27                67.21    59961   901.0   69007  ...                 51026
112               15.56   667475  1016.0  564931  ...                696516
..                  ...      ...     ...     ...  ...                   ...
582               22.64  4083339   926.0  198936  ...               6721420
584               13.79  2957447   952.0  330783  ...               2693022
585               13.96  2281090   954.0  463452  ...               2116037
586               15.68  8626883   955.0  798684  ...               8224779
589               20.89  5820469   937.0   84766  ...               4548459

        Religion2  Religion2 Population  religion3name  religion3poulation  \
6       2.Muslims               1576583   3.Christians               92915
14      2.Muslims                 71669   3.Christians               62227
17      2.Muslims                487839   3.Christians              131713
27   2.Christians                 36574       3.Others               25395
112      2.Others                  8644   3.Christians                6213
..            ...                   ...            ...                 ...
582     2.Muslims               2164058   3.Christians               20138
584      2.Others                251401      3.Muslims              239722
585      2.Others                226912      3.Muslims              180694
586     2.Muslims               1088618       3.Others              262578
589     2.Muslims               2295967   3.Christians               52835

     inhabitadevillages  drinkingwater  electricity  primary school  \
6           1016.451557     1009.67128   774.759516      796.794118
14          3108.000000     3091.00000  3098.000000     2293.000000
17           694.000000      694.00000   694.000000      690.000000
27           267.000000      267.00000    60.000000       69.000000
112         1220.000000     1204.00000   578.000000     1006.000000
..                  ...            ...          ...             ...
582         1572.000000     1567.00000  1274.000000     1391.000000
584         3577.000000     3548.00000  2214.000000     2663.000000
585         2468.000000     2452.00000  1232.000000     2135.000000
586        10548.000000    10475.00000  4835.000000     6133.000000
589         2087.000000     2079.00000  1322.000000     1774.000000

    Medical facility
6                118
14              1647
17               584
27                17
112              201
..               ...
582              955
584             1081
585             1173
586             3560
589             1311

[65 rows x 28 columns]

The output you’re seeing is a DataFrame that contains all the rows in your original dataset that were identified as outliers. These are the data points that significantly differ from other observations in your dataset.

The method you’ve used to detect outliers is likely based on the Z-score or IQR method. The Z-score method identifies an observation as an outlier if its Z-score (a measure of how many standard deviations an element is from the mean) is less than -3 or greater than 3. This means that the data points identified as outliers are those that are exceptionally low or high compared to the rest of the data.

In the output DataFrame, each row represents a district with various statistics such as population by gender, growth in population, literacy rate by gender, worker classification, and religious demographics. The districts listed in this DataFrame are those that have at least one statistic that is considered an outlier.

Remember, while outliers can skew your data, it’s important to investigate why they exist before deciding to remove them. They could be due to errors, but they could also be important, valid observations that indicate something significant about the phenomenon you’re studying.

# Dimensionality reduction

Dimensionality reduction is a technique used in machine learning to reduce the number of input variables in a dataset. High-dimensional data can be difficult to work with for several reasons. For example, it can lead to overfitting, it can be computationally expensive, and it can make visualizing the data challenging.

There are several methods for dimensionality reduction, including:

1. **Principal Component Analysis (PCA)**: This is a technique that transforms the data into a new coordinate system such that the greatest variance by any projection of the data comes to lie on the first coordinate (called the first principal component), the second greatest variance on the second coordinate, and so on.

2. **Linear Discriminant Analysis (LDA)**: This is a method used in statistics, pattern recognition, and machine learning to find a linear combination of features that characterizes or separates two or more classes of objects or events.

3. **t-Distributed Stochastic Neighbor Embedding (t-SNE)**: This is a technique for dimensionality reduction that is particularly well suited for the visualization of high-dimensional datasets.

4. **Autoencoders**: These are a type of artificial neural network used for learning efficient codings of input data. They can be used for dimensionality reduction.

5. **Feature selection methods**: These include techniques like backward elimination, forward selection, and bidirectional elimination.

Each of these methods has its own strengths and weaknesses, and is suitable for different types of tasks. The choice of method depends on the specific requirements of your task.

#### Dimensionality reduction using Principal Component Analysis (PCA) with Python’s sklearn library. PCA is a commonly used method for dimensionality reduction that transforms the original variables to a new set of variables, which are linear combinations of the original variables.

In [16]:

from sklearn.decomposition import PCA

# Select numeric columns
numeric_cols = df.select_dtypes(include=[np.number]).columns

# Normalize the numeric features
df_normalized = df.copy()
df_normalized[numeric_cols] = (df[numeric_cols] - df[numeric_cols].mean()) / df[numeric_cols].std()

# Fit and transform the data
pca = PCA(n_components=10)
df_pca = pca.fit_transform(df_normalized[numeric_cols])

# Convert the transformed data into a DataFrame
df_pca = pd.DataFrame(df_pca, columns=['PC' + str(i) for i in range(1, pca.n_components_+1)])

print(df_pca.head())

        PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0 -3.763857  2.077311 -0.158831  1.132385  1.947819 -0.050860  0.866245
1 -4.403762  1.136349 -0.021499 -0.500638  1.167866 -0.826715  1.413649
2  2.369451 -1.684128  0.376262 -1.335462  1.582645 -0.485059 -0.030763
3  1.254521 -0.850418 -0.744616 -2.381085  0.852039 -0.791409 -0.134390
4  3.635922 -0.343614 -1.067277 -2.245313  1.313231 -1.463458 -0.920197

        PC8       PC9      PC10
0 -0.073075  0.393618  0.049192
1 -1.102188  0.367812  0.144878
2  0.410876 -0.767453 -0.327471
3  0.626847 -0.463954 -0.278215
4  0.188523 -0.482735 -0.058430

The output you're seeing is the result of Principal Component Analysis (PCA), a technique used for dimensionality reduction. The goal of PCA is to create new features (the principal components) that maintain as much information as possible from the original data while reducing the dimensionality.

In our output:

- Each column labeled `PC1`, `PC2`, `PC3`, etc., represents a principal component. These are the new features created by PCA. They are linear combinations of your original features, chosen in such a way that each new feature is orthogonal (uncorrelated) to the ones before it, and that each feature explains as much of the remaining variance in your data as possible.
- Each row represents an observation (a district in your case) in your dataset, but in the transformed feature space.
- The numbers you see are the coordinates of your original data points (districts) along each of these new features. For example, the `-3.754562` under `PC1` for the first district means that this district is located at `-3.754562` along the `PC1` dimension.

Remember, the principal components are less interpretable than the original features, because they are combinations of all original features. However, they allow you to reduce the dimensionality of your data while keeping as much variance (information) as possible.

# Merging the two datasets

In [19]:
import pandas as pd

# Read both datasets
dataset1 = pd.read_csv("women-crimedataset-India (2).csv")
dataset2 = pd.read_csv("EDA2(District_name).csv")

# Convert 'state' and 'District' columns to lower case
dataset1['state'] = dataset1['state'].str.lower()
dataset1['District'] = dataset1['District'].str.lower()
dataset2['state'] = dataset2['state'].str.lower()
dataset2['District'] = dataset2['District'].str.lower()

# Merge datasets on 'state' and 'District'
merged_dataset = pd.merge(dataset1, dataset2, on=['state', 'District'])

# Print the merged dataset
print(merged_dataset)

# Write the merged dataset to a new CSV file
merged_dataset.to_csv("EDA3(Merged_dataset).csv", index=False)

      state District    YEAR MURDER ATTEMPT TO MURDER RAPE CUSTODIAL RAPE  \
0     assam  barpeta  2001.0     64                 5   28              0
1     assam  barpeta  2002.0     43                20   55              0
2     assam  barpeta  2003.0     46                 9   61              0
3     assam  barpeta  2004.0     48                 6   50              0
4     assam  barpeta  2005.0     38                 4   56              0
...     ...      ...     ...    ...               ...  ...            ...
2659  delhi    north  2020.0      0                 0   47              0
2660  delhi    south  2020.0      0                 0   74              0
2661  delhi     west  2020.0      1                 0   56              0
2662  delhi     west  2020.0      1                 0   56              0
2663  delhi     west  2020.0      1                 0   56              0

     OTHER RAPE KIDNAPPING & ABDUCTION  \
0            28                    105
1            55                     69
2            61                     76
3            50                     74
4            56                     69
...         ...                    ...
2659          0                    109
2660          0                    176
2661          0                    189
2662          0                    189
2663          0                    189

     KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS  ... religion1 population  \
0                                             88  ...               977943
1                                             59  ...               977943
2                                             56  ...               977943
3                                             60  ...               977943
4                                             66  ...               977943
...                                          ...  ...                  ...
2659                                         150  ...               609493
2660                                         183  ...              1824645
2661                                         217  ...              2540491
2662                                         217  ...              1745810
2663                                         217  ...              1612169

      Religion2 Religion2 Population religion3name religion3poulation  \
0     2.Muslims               662066  3.Christians               5267
1     2.Muslims               662066  3.Christians               5267
2     2.Muslims               662066  3.Christians               5267
3     2.Muslims               662066  3.Christians               5267
4     2.Muslims               662066  3.Christians               5267
...         ...                  ...           ...                ...
2659  2.Muslims               126093       3.Sikhs              20819
2660  2.Muslims               314015       3.Sikhs              75102
2661  2.Muslims               173409       3.Sikhs              91723
2662    2.Sikhs               247312     3.Muslims             107079
2663  2.Muslims                76429       3.Sikhs              29470

     inhabitadevillages  drinkingwater  electricity  primary school  \
0                1050.0         1050.0        775.0           967.0
1                1050.0         1050.0        775.0           967.0
2                1050.0         1050.0        775.0           967.0
3                1050.0         1050.0        775.0           967.0
4                1050.0         1050.0        775.0           967.0
...                 ...            ...          ...             ...
2659                5.0            5.0          4.0             3.0
2660               16.0           16.0         16.0            12.0
2661               62.0           62.0         62.0            57.0
2662                9.0            9.0          9.0             9.0
2663               51.0           51.0         51.0            49.0

      Medical facility
0                  430
1                  430
2                  430
3                  430
4                  430
...                ...
2659                 3
2660                 7
2661                44
2662                 5
2663                26

[2664 rows x 42 columns]